# Generated by Django 4.1.4 on 2023-02-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_appid', models.CharField(max_length=3, unique=True)),
                ('app_name', models.CharField(max_length=15)),
                ('app_description', models.CharField(max_length=100)),
                ('app_status', models.BooleanField()),
                ('app_link', models.CharField(max_length=60)),
                ('app_usertypeauth', models.CharField(max_length=1)),
                ('app_startdate', models.DateField()),
                ('app_enddate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app',
            },
        ),
        migrations.CreateModel(
            name='ChangePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_userprogr', models.IntegerField(blank=True, default=0, null=True)),
                ('phone_status', models.CharField(choices=[('list of value', 'list of value')], max_length=20)),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=20)),
                ('phone_endverification', models.DateTimeField(blank=True, null=True)),
                ('phone_endvalidity', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'change_phone',
            },
        ),
        migrations.CreateModel(
            name='CommunityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmty_ownerid', models.IntegerField(blank=True, default=0, null=True)),
                ('cmty_country', models.CharField(max_length=2)),
                ('cmty_memberid', models.IntegerField(blank=True, default=0, null=True)),
                ('cmty_cmtylevel', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('cmty_status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('C', 'Cancelled')], max_length=1)),
                ('cmty_insertdate', models.DateTimeField(auto_now_add=True)),
                ('cmty_lastupdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('comp_prog', models.IntegerField(primary_key=True, serialize=False)),
                ('comp_mail', models.CharField(blank=True, max_length=50, null=True)),
                ('comp_name', models.CharField(blank=True, max_length=100, null=True)),
                ('comp_address', models.CharField(blank=True, max_length=200, null=True)),
                ('comp_legalrepprogr', models.IntegerField(blank=True, null=True)),
                ('comp_legalrepname', models.CharField(blank=True, max_length=30, null=True)),
                ('comp_legalrepsurname', models.CharField(blank=True, max_length=30, null=True)),
                ('comp_legalrpcountry', models.CharField(blank=True, max_length=2, null=True)),
                ('comp_legalrepmail', models.CharField(blank=True, max_length=50, null=True)),
                ('comp_legalrepdocimgfrontid', models.CharField(blank=True, max_length=10, null=True)),
                ('comp_legalrepdocimgackid', models.CharField(blank=True, max_length=10, null=True)),
                ('comp_vatcode', models.CharField(blank=True, max_length=30, null=True)),
                ('comp_sectorid', models.CharField(blank=True, max_length=3, null=True)),
                ('comp_legalrepdocendvalidity', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('cus_progr', models.IntegerField(primary_key=True, serialize=False)),
                ('cus_name', models.CharField(blank=True, max_length=30, null=True)),
                ('cus_surname', models.CharField(blank=True, max_length=30, null=True)),
                ('cus_address', models.CharField(blank=True, max_length=200, null=True)),
                ('cus_birthdate', models.DateField(blank=True, null=True)),
                ('cus_docimgfrontid', models.CharField(blank=True, max_length=10, null=True)),
                ('cus_docimgackid', models.CharField(blank=True, max_length=10, null=True)),
                ('cus_residenceproofimg', models.CharField(blank=True, max_length=10, null=True)),
                ('cus_docendvalidity', models.DateField(blank=True, null=True)),
                ('cus_nationalid', models.CharField(blank=True, max_length=30, null=True)),
                ('cus_companyprogr', models.IntegerField(blank=True, null=True)),
                ('cus_companyrole', models.CharField(blank=True, choices=[('list of value', 'list of value')], max_length=15, null=True)),
                ('cus_companyauthlevel', models.CharField(blank=True, choices=[('list of value', 'list of value')], default=0, max_length=15, null=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='ExpertModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('exp_prog', models.IntegerField()),
                ('expert_mail', models.EmailField(max_length=254, unique=True)),
                ('business_name', models.CharField(max_length=30)),
                ('document_type', models.CharField(max_length=2)),
                ('document_id', models.CharField(max_length=15)),
                ('document_image_front', models.ImageField(upload_to='')),
                ('document_image_back', models.ImageField(upload_to='')),
                ('vat_code', models.CharField(max_length=30)),
                ('job_sector_id', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'expert',
            },
        ),
        migrations.CreateModel(
            name='LanguageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='PasswordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passwordPassword', models.CharField(max_length=50)),
                ('passwordUserProg', models.IntegerField()),
                ('passworduserMail', models.CharField(max_length=50)),
                ('passwordStatus', models.CharField(max_length=1)),
                ('passwordLastLogin', models.DateTimeField()),
                ('passwordEndDate', models.DateTimeField()),
                ('passwordStartDate', models.DateTimeField()),
                ('passwordCterr', models.IntegerField()),
            ],
            options={
                'db_table': 'password',
            },
        ),
        migrations.CreateModel(
            name='PlanApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=10, unique=True)),
                ('app_code', models.CharField(max_length=3, unique=True)),
                ('status', models.BooleanField()),
                ('plan_name', models.CharField(max_length=10)),
                ('currency', models.CharField(max_length=3)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration', models.PositiveSmallIntegerField()),
                ('duration_type', models.CharField(max_length=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plan_app',
            },
        ),
        migrations.CreateModel(
            name='PlanDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=10)),
                ('row_progr', models.PositiveSmallIntegerField(unique=True)),
                ('field_name', models.CharField(max_length=10)),
                ('field_type', models.CharField(max_length=1)),
                ('field_value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'plan_details',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=10, unique=True)),
                ('app_code', models.CharField(max_length=3, unique=True)),
                ('status', models.BooleanField()),
                ('profile_name', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_promocode', models.CharField(max_length=10, unique=True)),
                ('promo_appid', models.CharField(max_length=3, unique=True)),
                ('promo_desc', models.CharField(max_length=100)),
                ('promo_status', models.BooleanField()),
                ('promo_startdate', models.DateField()),
                ('promo_enddate', models.DateField()),
            ],
            options={
                'db_table': 'promo_code',
            },
        ),
        migrations.CreateModel(
            name='RewardsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hrew_userid', models.IntegerField(blank=True, default=0, null=True)),
                ('hrew_period', models.CharField(blank=True, max_length=7, null=True)),
                ('hrew_country', models.CharField(blank=True, max_length=2, null=True)),
                ('hrew_friendscount', models.IntegerField(blank=True, null=True)),
                ('hrew_cmtycount', models.IntegerField(blank=True, null=True)),
                ('hrew_userrp', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('hrew_cmtyrp', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('hrew_userevel', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('hrew_levelperc', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hrew_userearn', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('hrew_insertdate', models.DateTimeField(auto_now_add=True)),
                ('hrew_lastupdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userProg', models.IntegerField()),
                ('appID', models.IntegerField()),
                ('userStatus', models.IntegerField()),
            ],
            options={
                'db_table': 'user_app',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_Prog', models.AutoField(primary_key=True, serialize=False)),
                ('user_Mail', models.CharField(max_length=50, unique=True)),
                ('user_CountryCode', models.CharField(max_length=2)),
                ('user_PresenterID', models.IntegerField(blank=True, default=0, null=True)),
                ('user_mailStatus', models.CharField(default='N', max_length=1)),
                ('user_Status', models.IntegerField(blank=True, null=True)),
                ('user_phonePrefix', models.CharField(blank=True, max_length=7, null=True)),
                ('user_Language', models.CharField(blank=True, max_length=2, null=True)),
                ('user_phoneNumber', models.IntegerField(blank=True, null=True)),
                ('user_acceptTermsCondition', models.CharField(blank=True, default='N', max_length=1)),
                ('user_acceptPrivacy', models.CharField(blank=True, default='N', max_length=1)),
                ('user_acceptStatistics', models.CharField(blank=True, default='N', max_length=1)),
                ('user_promoCode', models.CharField(blank=True, default='N', max_length=10)),
                ('user_userID', models.CharField(blank=True, max_length=50, null=True)),
                ('user_functionType', models.CharField(blank=True, max_length=1, null=True)),
                ('user_Type', models.CharField(blank=True, max_length=2, null=True)),
                ('user_mail2', models.CharField(blank=True, max_length=50, null=True)),
                ('user_maildelegat', models.CharField(blank=True, max_length=50, null=True)),
                ('user_phonenumber2', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('user_username', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserPayMet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(unique=True)),
                ('payment_method', models.CharField(max_length=3)),
                ('payment_method_progr', models.PositiveSmallIntegerField(unique=True)),
                ('payment_method_id', models.CharField(max_length=30)),
                ('payment_method_user_note', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'user_pay_met',
            },
        ),
        migrations.CreateModel(
            name='VerificationCodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verUserProg', models.IntegerField()),
                ('verCodeType', models.CharField(max_length=1)),
                ('verStartDate', models.DateTimeField()),
                ('verEndDate', models.DateTimeField()),
                ('verlastLoginerr', models.DateTimeField(blank=True, null=True)),
                ('verstatus', models.CharField(max_length=1)),
                ('vercterr', models.IntegerField(blank=True, null=True)),
                ('verlasttentative', models.DateTimeField(blank=True, null=True)),
                ('verificationCode', models.CharField(default='000000', max_length=6)),
            ],
            options={
                'db_table': 'verification_code',
            },
        ),
    ]
