# Generated by Django 4.1.4 on 2023-02-01 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='communitymodel',
            table='community',
        ),
        migrations.AlterModelTable(
            name='rewardsmodel',
            table='rewards',
        ),
        migrations.AlterModelTable(
            name='userpaymet',
            table='paymet',
        ),
    ]
