# Generated by Django 4.1.4 on 2023-02-02 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_value_countrymodel_country_coutrycode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrymodel',
            old_name='country_countryname',
            new_name='country_name',
        ),
    ]
